#DEV environment
app:
  message=This is the property DEV for the ${spring.application.name}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${ENV_DB_URL}
    username: sa
    password: sa